using System;
using Unity.Networking.Transport;
using UnityEngine;

public abstract class NetSender : MonoBehaviour
{
    public int Id;
    public int? ConnectionId = null;
    public int? InstanceId;

    public int UpdateFrame { get; set; } = 5;
    public int CurrentFrame { get; set; }

    public abstract DataStreamWriter GetNew();
    public abstract DataStreamWriter Write(DataStreamWriter stream);
}

public abstract class NetReader : MonoBehaviour
{
    public int Id;

    /// <summary>
    /// When generated by the server as a ghost, the connecction ID will be assign.
    /// </summary>
    public int? ConnectionId = null;
    public int? InstanceId { get; set; }

    public bool Log;

    public abstract void Read(int connectionId, DataStreamReader stream, ref DataStreamReader.Context context);
}
